server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
       defaultZone: http://eureka7003.com:7003/eureka/




