server:
  port: 8002


spring:
  application:
    name: xcx-cloud-consumer-service
  zipkin:
      #启动zipServer对应的jar包时访问的地址
      #也就是注册到这个监控平台 可以到上看到
      base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率介于0-1之间，1表示全部采集，一般用0.5
      probability: 1
eureka:
  client:
    register-with-eureka: true #false表示自己不往注册中心注册
    #false表示自己端就是注册中心，自己就是用来维护服务实例的，不需要去检索服务
    #客户端需要设置为true,单节点无所谓，但是如果是集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #服务注册地址,即为Eureka的服务端设定的defaultZone地址
    service-url:
      #单机版到对应的注册中心就可以
        #defaultZone: http://localhost:7001/eureka
      #集群版本
        defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7002.com:7002/eureka/
#自定义属性
restTemplate:
    #单机版
    #url: http://localhost:8001
    #服务提供者集群版，进入Eureka注册中心查看服务名称,必须带上http://
    url: http://XCX-CLOUD-PAYMENT-SERVICE
