server:
  port: 8008


spring:
  application:
    name: xcx-cloud-consumer-service
eureka:
  client:
    register-with-eureka: false #false表示自己不往注册中心注册
    #false表示自己端就是注册中心，自己就是用来维护服务实例的，不需要去检索服务
    #客户端需要设置为true,单节点无所谓，但是如果是集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #服务注册地址,即为Eureka的服务端设定的defaultZone地址
    service-url:
      #单机版到对应的注册中心就可以
        #defaultZone: http://localhost:7001/eureka
      #集群版本
        defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7002.com:7002/eureka/
#设置客户端超时时间
ribbon:
   ReadTimeout: 5000 #客户端与服务端建立连接所需要的时间
   ConnectTimeout: 5000 #建立连接后从服务端获取数据的时间
#设置Feign日志
logging:
  level:
     com.xcx.springcloud.feign.confi.FeignConfig: debug