server:
  port: 8006

spring:
  application:
    name:  xcx-cloud-consul-payment-service #服务名称,注册到consul中心的名称，配置集群的时候服务名称保持一致
   # consul注册中心
  cloud:
    consul:
      host: 192.168.40.128 #安装consul服务器地址
      port: 8500 #consul端口号
      discovery: ${spring.application.name}
