server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureak服务端的实例名称
  client:
    register-with-eureka: false #false表示自己不往注册中心注册
    fetch-registry: false  #false表示自己端就是注册中心，自己就是用来维护服务实例的，不需要去检索服务
    #查询服务注册信息地址 前面必须加上http:// ,注册地址后面必须带上eureka
    service-url:
      #单机版的指定地址为：
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #如果是Eureka集群相互注册 相互守望，则此处需要改成另外一个Eureka指定的地址，此处为eureka7002.com
      #如果有多个通过逗号分隔如defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/
  #server:
    #enable-self-preservation: false #关闭自我保护机制
    #eviction-interval-timer-in-ms: 2000 #指定时间 毫秒,多少时间内没检查到心跳包就删除注册中心中的服务


